export enum AUTH_TYPES {
  SET_USER = 'SET_USER',
}

export enum PROFILE_TYPES {
  SET_PROFILE = 'SET_PROFILE',
}

export enum ALERT_TYPES {
  SET_ALERT = 'SET_ALERT',
  REMOVE_ALERT = 'REMOVE_ALERT',
}
